<?php

/**
 * @file
 */

require_once('location_taxonomize_af.inc');

function location_taxonomize_af_field_widget_info_alter(&$info) {
  dpm('1');
  dpm($info);
  // Add a setting to a widget type.
  $info['addressfield_standard']['settings'] += array(
    'location_taxonomize' => 0,
  );
  dpm($info);
}

function location_taxonomize_af_form_field_ui_field_edit_form_alter(&$form, $form_state, $form_id) {
  dpm('2');
  //dpm($form['#field']);
  if ($form['#field']['type'] != 'addressfield') return;  // only applies for references fields
  
  $settings = $form['#instance']['widget']['settings'];
  dpm($settings);
  $enable = array(
    '#type'           => 'checkbox',
    '#title'          => t('Taxonomize locations from this field using Location Taxonomize'),
    '#default_value'  => $settings['location_taxonomize'],
  );
  $form['instance']['widget']['settings']['location_taxonomize'] = $enable;
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function location_taxonomize_af_field_widget_addressfield_standard_form_alter(&$element, &$form_state, $context) {
  //dpm('widget form alter');
  dpm($context);
  // apply this only if we are on a node-edit form
  if (!isset($context['form']['#node_edit_form'])) return;
  // check field settings
  $taxonomize = $context['instance']['widget']['settings']['location_taxonomize'];
  // add a process function to addressfield widgets
  if ($taxonomize) {
    $element['#process'][] = 'location_taxonomize_af_process_address';
  }
}

/**
 * A #process callback function for the addressfield widget
 */
function location_taxonomize_af_process_address($element, &$form_state, &$form) {
  dpm('process callback');
  //dpm($element);
  // add a submit handler to forms that have this widget
  $form['#submit'][] = 'location_taxonomize_af_element_submitted';
  // make note that this field needs to be processed in the submit handler
  $form_state['temporary']['addressfields'][] = $element['#field_name'];
  return $element;
}

/**
 * A submit handler for forms that contain an addressfield
 */
function location_taxonomize_af_element_submitted($form, &$form_state) {
  $lang = 'und';
  // Act on values
  //dpm($form_state);
  $fields = $form_state['temporary']['addressfields'];
  foreach ($fields as $field) {
    $deltas = $form_state['values'][$field][$lang];
    foreach ($deltas as $delta) {
       // Process field
      location_taxonomize_af_process_item($delta);
    }
  }
}

/**
 * Central function that processes an addressfield item and sends it to 
 * Location Taxonomize to be saved into the taxonomy
 */
function location_taxonomize_af_process_item($address) {
  dpm('processing address');
  //dpm($address);
}