<?php

/*
 * @file
 * Installer
 */

require_once('location_taxonomize_location.inc');

/**
 * Implements hook_install().
 */
function location_taxonomize_location_install() {
  _location_taxonomize_location_set_defaults();
  variable_set('location_taxonomize_source', 'location_taxonomize_location');
}

/**
 * Implements hook_enable().
 */
function location_taxonomize_location_enable() {
  // ...
}

/**
 * Implements hook_requirements().
 */
function location_taxonomize_location_requirements($phase) {
  $requirements = array();
  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function location_taxonomize_location_uninstall() {
  // delete all variables created by this modules
  _location_taxonomize_location_del_variables();
}

